asr:
  model_id: openai/whisper-small
benchmark:
  enable_streaming_audio: false
  save_processed_samples: false
dataset:
  name: globe
  num_samples: 20
  split: test
  warmup_samples: 3
experiment:
  description: Default pipeline with STT -> LLM -> TTS
  name: baseline
llm:
  kv_cache: false
  max_new_tokens: 100
  model_id: Qwen/Qwen2.5-3B-Instruct
  quantization:
    compute_dtype: bf16
    enabled: true
    load_in_4bit: true
    quant_type: nf4
    use_double_quant: true
tts:
  language: en
  model_id: tts_models/multilingual/multi-dataset/xtts_v2
  model_name: xtts
  speaker: Gracie Wise
